# ===============================
# SERVER
# ===============================
server.port=8082
spring.application.name=shipment-consumer

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=order-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Desativa auto commit (melhor pr\u00e1tica)
spring.kafka.consumer.enable-auto-commit=false

# ===============================
# LISTENER
# ===============================
spring.kafka.listener.ack-mode=manual
spring.kafka.listener.concurrency=1

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=outbox
spring.datasource.password=outbox
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Dialeto recomendado para Postgres 16+
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.type.json_format_mapper=br.com.mystore.shipment.repository.utils.JsonFormatter
# ===============================
# CONNECTION POOL (Hikari)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ===============================
# JACKSON
# ===============================
spring.jackson.default-property-inclusion=non_null

# ===============================
# LOGGING
# ===============================
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO